name: Android CI

on:
  workflow_dispatch:
    inputs:
      project_path:
        description: 'The path to the customized project'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: 30.0.3

    - name: Build with Gradle
      run: ./gradlew build -p ${{ github.event.inputs.project_path }}

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: ${{ github.event.inputs.project_path }}/app/build/outputs/apk/release/app-release.apk
